package aistudio

import (
	"context"
	"encoding/json"
	"time"
)

// Role represents a canonical message role
type Role string

const (
	// RoleUser indicates a user message
	RoleUser Role = "user"
	// RoleAssistant indicates a model message
	RoleAssistant Role = "assistant"
	// RoleTool indicates a tool result message
	RoleTool Role = "tool"
)

// Blob represents inline binary content
type Blob struct {
	MIME string `json:"mime"`
	Data []byte `json:"data"`
}

// ExternalMedia represents external media directly readable by AI Studio
type ExternalMedia struct {
	MIME string `json:"mime"`
	URL  string `json:"url"`
}

// FileRef represents an uploaded file reference
type FileRef struct {
	ID   string `json:"id"`
	Name string `json:"name,omitempty"`
	MIME string `json:"mime,omitempty"`
}

// FunctionCall represents a function call initiated by the model
type FunctionCall struct {
	ID               string          `json:"id"`
	Name             string          `json:"name"`
	Arguments        json.RawMessage `json:"arguments"`
	ThoughtSignature string          `json:"thought_signature,omitempty"`
}

// FunctionResult represents a function result returned by the client
type FunctionResult struct {
	ID      string          `json:"id"`
	Name    string          `json:"name,omitempty"`
	Content json.RawMessage `json:"content"`
}

// ExecutableCode represents code generated by AI Studio's built-in code execution
type ExecutableCode struct {
	Language string `json:"language"`
	Code     string `json:"code"`
}

// CodeExecutionResult represents the outcome returned by AI Studio's built-in code execution
type CodeExecutionResult struct {
	Outcome string `json:"outcome"`
	Output  string `json:"output,omitempty"`
	Error   string `json:"error,omitempty"`
}

// SearchEntryPoint represents the search entry point returned by Google Search
type SearchEntryPoint struct {
	RenderedContent string `json:"rendered_content,omitempty"`
	SDKBlob         string `json:"sdk_blob,omitempty"`
}

// GroundingChunk represents a source retrieved by Google tools
type GroundingChunk struct {
	Source  string `json:"source"`
	URI     string `json:"uri,omitempty"`
	Title   string `json:"title,omitempty"`
	Text    string `json:"text,omitempty"`
	PlaceID string `json:"place_id,omitempty"`
}

// GroundingSegment represents a text segment supported by sources
type GroundingSegment struct {
	PartIndex  int    `json:"part_index,omitempty"`
	StartIndex int    `json:"start_index,omitempty"`
	EndIndex   int    `json:"end_index,omitempty"`
	Text       string `json:"text,omitempty"`
}

// GroundingSupport represents the association between text segments and source indices
type GroundingSupport struct {
	Segment          GroundingSegment `json:"segment"`
	ChunkIndices     []int            `json:"chunk_indices,omitempty"`
	ConfidenceScores []float64        `json:"confidence_scores,omitempty"`
}

// GroundingMetadata represents grounding information for Google Search, URL Context, and Maps
type GroundingMetadata struct {
	SearchEntryPoint       *SearchEntryPoint  `json:"search_entry_point,omitempty"`
	Chunks                 []GroundingChunk   `json:"chunks,omitempty"`
	Supports               []GroundingSupport `json:"supports,omitempty"`
	DynamicRetrievalScore  *float64           `json:"dynamic_retrieval_score,omitempty"`
	WebSearchQueries       []string           `json:"web_search_queries,omitempty"`
	MapsWidgetContextToken string             `json:"maps_widget_context_token,omitempty"`
}

// Part represents a content block in a canonical message
type Part struct {
	Text                string               `json:"text,omitempty"`
	InlineData          *Blob                `json:"inline_data,omitempty"`
	ExternalMedia       *ExternalMedia       `json:"external_media,omitempty"`
	File                *FileRef             `json:"file,omitempty"`
	FunctionCall        *FunctionCall        `json:"function_call,omitempty"`
	FunctionResult      *FunctionResult      `json:"function_result,omitempty"`
	ExecutableCode      *ExecutableCode      `json:"executable_code,omitempty"`
	CodeExecutionResult *CodeExecutionResult `json:"code_execution_result,omitempty"`
	Thought             bool                 `json:"thought,omitempty"`
	ThoughtSignature    string               `json:"thought_signature,omitempty"`
}

// Content represents a canonical message
type Content struct {
	Role  Role   `json:"role"`
	Parts []Part `json:"parts"`
}

// FunctionDeclaration represents a function declared by the client
type FunctionDeclaration struct {
	Name        string          `json:"name"`
	Description string          `json:"description,omitempty"`
	Parameters  json.RawMessage `json:"parameters,omitempty"`
}

// ToolConfig represents a tool enablement policy
type ToolConfig struct {
	Mode string `json:"mode,omitempty"`
}

// GoogleSearchTimeRange represents the retrieval time range for Google Search
type GoogleSearchTimeRange struct {
	StartTime time.Time `json:"start_time,omitzero"`
	EndTime   time.Time `json:"end_time,omitzero"`
}

// GoogleSearchOptions represents retrieval types and time ranges for Google Search
type GoogleSearchOptions struct {
	WebSearch   bool                   `json:"web_search,omitempty"`
	ImageSearch bool                   `json:"image_search,omitempty"`
	TimeRange   *GoogleSearchTimeRange `json:"time_range,omitempty"`
}

// Tools represents tools enabled for a request
type Tools struct {
	Functions    []FunctionDeclaration `json:"functions,omitempty"`
	Google       []string              `json:"google,omitempty"`
	GoogleSearch *GoogleSearchOptions  `json:"google_search,omitempty"`
	ToolConfig   ToolConfig            `json:"tool_config,omitempty"`
}

// ResponseModality represents a model output modality
type ResponseModality string

const (
	// ResponseModalityText indicates text output
	ResponseModalityText ResponseModality = "TEXT"
	// ResponseModalityImage indicates image output
	ResponseModalityImage ResponseModality = "IMAGE"
	// ResponseModalityAudio indicates audio output
	ResponseModalityAudio ResponseModality = "AUDIO"
)

// ImageConfig represents image generation parameters
type ImageConfig struct {
	AspectRatio string `json:"aspect_ratio,omitempty"`
	ImageSize   string `json:"image_size,omitempty"`
}

// SpeakerVoiceConfig represents voice selection for multi-speaker synthesis
type SpeakerVoiceConfig struct {
	Speaker   string `json:"speaker"`
	VoiceName string `json:"voice_name"`
}

// SpeechConfig represents speech generation parameters
type SpeechConfig struct {
	VoiceName string               `json:"voice_name,omitempty"`
	Speakers  []SpeakerVoiceConfig `json:"speakers,omitempty"`
}

// TranscriptionConfig represents audio transcription parameters
type TranscriptionConfig struct {
	WordTimestamps     bool     `json:"word_timestamps,omitempty"`
	SpeakerLabels      bool     `json:"speaker_labels,omitempty"`
	CustomVocabulary   []string `json:"custom_vocabulary,omitempty"`
	LanguageCodes      []string `json:"language_codes,omitempty"`
	SmartTranscription bool     `json:"smart_transcription,omitempty"`
}

// GenerationConfig represents validated generation parameters
type GenerationConfig struct {
	Temperature         *float64             `json:"temperature,omitempty"`
	TopP                *float64             `json:"top_p,omitempty"`
	TopK                *int                 `json:"top_k,omitempty"`
	MaxOutputTokens     *int64               `json:"max_output_tokens,omitempty"`
	StopSequences       []string             `json:"stop_sequences,omitempty"`
	ResponseMIMEType    string               `json:"response_mime_type,omitempty"`
	ResponseSchema      json.RawMessage      `json:"response_schema,omitempty"`
	ResponseModalities  []ResponseModality   `json:"response_modalities,omitempty"`
	ImageConfig         *ImageConfig         `json:"image_config,omitempty"`
	SpeechConfig        *SpeechConfig        `json:"speech_config,omitempty"`
	TranscriptionConfig *TranscriptionConfig `json:"transcription_config,omitempty"`
	ReasoningEffort     string               `json:"reasoning_effort,omitempty"`
	ThinkingBudget      *int64               `json:"thinking_budget,omitempty"`
	Seed                *int64               `json:"seed,omitempty"`
}

// GenerateRequest represents a provider-agnostic generation request
type GenerateRequest struct {
	ID        string           `json:"id"`
	Model     string           `json:"model"`
	System    string           `json:"system,omitempty"`
	Contents  []Content        `json:"contents"`
	Config    GenerationConfig `json:"config,omitempty"`
	Tools     Tools            `json:"tools,omitempty"`
	AccountID string           `json:"account_id,omitempty"`
}

// TokenCountRequest represents a token counting request
type TokenCountRequest struct {
	Model    string    `json:"model"`
	System   string    `json:"system,omitempty"`
	Contents []Content `json:"contents"`
	Tools    Tools     `json:"tools,omitempty"`
}

// TokenCount represents authoritative token counts returned by upstream
type TokenCount struct {
	InputTokens int64 `json:"input_tokens"`
}

// Model represents a model in the live model catalog
type Model struct {
	ID                string              `json:"id"`
	Name              string              `json:"name"`
	Description       string              `json:"description,omitempty"`
	Methods           []string            `json:"methods"`
	InputTokenLimit   int64               `json:"input_token_limit,omitempty"`
	OutputTokenLimit  int64               `json:"output_token_limit,omitempty"`
	Capabilities      map[string]bool     `json:"capabilities,omitempty"`
	CapabilityOptions map[string][]string `json:"capability_options,omitempty"`
	AccessModes       []int64             `json:"access_modes,omitempty"`
	Paid              bool                `json:"paid,omitempty"`
}

// Usage represents token usage for a single generation
type Usage struct {
	InputTokens         int64 `json:"input_tokens"`
	OutputTokens        int64 `json:"output_tokens"`
	ReasoningTokens     int64 `json:"reasoning_tokens,omitempty"`
	ToolTokens          int64 `json:"tool_tokens,omitempty"`
	TotalTokens         int64 `json:"total_tokens"`
	OutputTokensMissing bool  `json:"-"`
}

// Citation represents a source citation returned by the model
type Citation struct {
	URL       string `json:"url"`
	Title     string `json:"title,omitempty"`
	Start     int    `json:"start,omitempty"`
	End       int    `json:"end,omitempty"`
	Publisher string `json:"publisher,omitempty"`
}

// Media represents a generated media artifact
type Media struct {
	URL      string `json:"url,omitempty"`
	Data     []byte `json:"data,omitempty"`
	MIME     string `json:"mime,omitempty"`
	Name     string `json:"name,omitempty"`
	Width    int    `json:"width,omitempty"`
	Height   int    `json:"height,omitempty"`
	Duration int64  `json:"duration_ms,omitempty"`
}

// TranscriptDuration represents a transcription duration value
type TranscriptDuration struct {
	Seconds int64 `json:"seconds"`
	Nanos   int64 `json:"nanos,omitempty"`
}

// TranscriptTimestamp represents a time range for transcript text
type TranscriptTimestamp struct {
	Start TranscriptDuration `json:"start"`
	End   TranscriptDuration `json:"end"`
}

// TranscriptMetadata represents speaker and timing information attached to transcript text
type TranscriptMetadata struct {
	Text       string                `json:"text"`
	Speaker    string                `json:"speaker,omitempty"`
	Timestamps []TranscriptTimestamp `json:"timestamps,omitempty"`
}

// EventKind represents canonical stream event kinds
type EventKind string

const (
	// EventText indicates text delta
	EventText EventKind = "text"
	// EventReasoning indicates reasoning summary delta
	EventReasoning EventKind = "reasoning"
	// EventToolCall indicates a function call
	EventToolCall EventKind = "tool_call"
	// EventExecutableCode indicates code generated by the built-in code executor
	EventExecutableCode EventKind = "executable_code"
	// EventCodeExecutionResult indicates execution result from the built-in code executor
	EventCodeExecutionResult EventKind = "code_execution_result"
	// EventGrounding indicates grounding info from Google tools
	EventGrounding EventKind = "grounding"
	// EventCitation indicates citation information
	EventCitation EventKind = "citation"
	// EventMedia indicates a media artifact
	EventMedia EventKind = "media"
	// EventThoughtSignature indicates an independent thought signature
	EventThoughtSignature EventKind = "thought_signature"
	// EventUsage indicates authoritative usage
	EventUsage EventKind = "usage"
	// EventFinish indicates normal completion
	EventFinish EventKind = "finish"
	// EventError indicates an upstream error
	EventError EventKind = "error"
)

// Event represents a canonical event emitted by protocol core
type Event struct {
	Kind                EventKind            `json:"kind"`
	Text                string               `json:"text,omitempty"`
	ToolCall            *FunctionCall        `json:"tool_call,omitempty"`
	ExecutableCode      *ExecutableCode      `json:"executable_code,omitempty"`
	CodeExecutionResult *CodeExecutionResult `json:"code_execution_result,omitempty"`
	Grounding           *GroundingMetadata   `json:"grounding,omitempty"`
	Citation            *Citation            `json:"citation,omitempty"`
	Media               *Media               `json:"media,omitempty"`
	Transcript          *TranscriptMetadata  `json:"transcript,omitempty"`
	Usage               *Usage               `json:"usage,omitempty"`
	FinishReason        string               `json:"finish_reason,omitempty"`
	StopSequence        string               `json:"stop_sequence,omitempty"`
	ProviderModel       string               `json:"provider_model,omitempty"`
	ThoughtSignature    string               `json:"thought_signature,omitempty"`
	Err                 error                `json:"-"`
}

// Service defines the minimal capabilities required by public protocol adapters
type Service interface {
	Models(context.Context) ([]Model, error)
	CountTokens(context.Context, TokenCountRequest) (TokenCount, error)
	Generate(context.Context, GenerateRequest) (<-chan Event, error)
}
